### PR TITLE
Beautified Demo Page

### LINKED ISSUE #63: Make the Demo Page look nice
The demo page should have all the components on it and ordered alphabetically using nice examples. 

- This is a great issue for someone who isn't feeling 100% comfortable yet and wants to become more familiar with the existing components

### PR DESCRIPTION
**Pull request by dynomite567**
Fixes #63

### CODE REVIEW

**Comment by NehemiahK** [comment]
Hey, do you think you can resolve the conflicts @dynomite567

**Comment by dynomite567** [comment]
Done. All Conflicts have been merged.

**Comment by NehemiahK** [comment]
still has conflicts

**Comment by dynomite567** [comment]
Conflicts have been fixed again. Ready to be merged.

**Comment by NehemiahK** [comment]
thank you

**Pull request merged**
