### PR TITLE
Added Modal using React.js portal

### PR DESCRIPTION
**Pull request by raghubandaru**
Re-implemented Modal Dialog without the need of any third-party library.

### CODE REVIEW

**Comment by NehemiahK** [comment]
I see you used "demo" as the selector , could we change that? since users wouldn't be using demo

**Comment by raghubandaru** [comment]
I am new using nwb, and there is no index.html file to add another id which is required for portal. Where can I add this?

**Comment by NehemiahK** [comment]
well the library will simply be imported, they wouldn't be able to use this component if it's relying on something that isn't there. 
Why does this need to use portal? I would imagine the usage would be you have lets say App and you import {Modal} 

Then you can use <Modal content={content} onOpen={} onClose={} /> 

Something along those lines?

**Comment by raghubandaru** [comment]
Thanks for the helpful insights. It helped me in thinking about the problem better.

1. Why portals? We are building a Modal and we are displaying component that is nested to take the precedence. 

2. Solution for now I can think is: User importing our Modal, creating the required dom element on his side and pass the reference to the Modal we are building. This is the reason I used demo, I think I need to refactor to passing reference in the Modal. (User may name root or by some other name)

Guide me if I am missing something, I will start implementing once I get time.

**Comment by NehemiahK** [comment]
That sounds like it makes more sense to me

**Comment by raghubandaru** [comment]
Is the recent implementation aligns with your expectations?

And by the way I would like to know how and who is generating index.html for our project.

**Comment by NehemiahK** [comment]
Seems to align. The project isn't meant to have an index. 
It's just like importing React or any other library. 
Although I guess create-react-app comes with an index. but all this library does is allow you to import components, so there is no index.html

**Comment by raghubandaru** [comment]
Hi NehemiahK,

Did you find any better implementation? Anyways had great time about looking into nwb and getting my feet in open source software.

**Pull request closed without merging**
