### PR TITLE
spinner component

### PR DESCRIPTION
**Pull request by manjeetaR**
Addresses the issue #109 

Customized size, speed, color, background color and thickness.

### CODE REVIEW

**Comment by NehemiahK** [comment]
thanks can you resolve the conflicts

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Comment by manjeetaR** [comment]
> thanks can you resolve the conflicts

@NehemiahK Conflicts Resolved, could you review it please.

**Comment by NehemiahK** [comment]
the spinner has conflicts as well in the css and js

**Comment by manjeetaR** [comment]
> the spinner has conflicts as well in the css and js

@NehemiahK Conflicts resolved

**Pull request merged**
