### PR TITLE
Add Favourite component

### PR DESCRIPTION
**Pull request by benszucs**
Hi, @NehemiahK just re-uploaded the Favourite component for [#87](https://github.com/NehemiahK/Another-React-Lib/issues/87)

### CODE REVIEW

**Comment by NehemiahK** [comment]
thanks can you fix the conflicts

**Comment by benszucs** [comment]
This is my first pull request so am a bit lost... How is the best way to solve conflicts? Would it be through the local repo I was developing on or through the website here on github? Any pointers are welcome :) cheers

**Comment by NehemiahK** [comment]
The easiest way is to copy what is on master for these files and just overwrite your changes and use what's on master

**Comment by benszucs** [comment]
Thanks @NehemiahK that was simple enough :) hope all is good now

**Comment by NehemiahK** [comment]
still shows conflicts

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Comment by benszucs** [comment]
[#87](https://github.com/NehemiahK/Another-React-Lib/issues/87)
I reset the branch and only added the component. hope it's ok

**Comment by NehemiahK** [comment]
perfect

**Pull request merged**
