### PR TITLE
#107 update switch state handling and styling

### PR DESCRIPTION
**Pull request by austinaryain**
I updated the switch state handling into two separate methods and changed the span color to Green (#51e83a) when the state is checked.

### CODE REVIEW

**Comment by NehemiahK** [comment]
@austinaryain please resolve the conflicting files: src/index and demo/src/index

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Comment by austinaryain** [comment]
Yeah I'll do that, I ended up having to touch the index files to get it to build due to some missing components in there, but I'll make it consistent. 

I also had to update the state handling for the switches in the demo index so they don't toggle each other. Is that okay or should I leave that one too?

**Comment by NehemiahK** [comment]
Leave whatever is in the index files as they are,

**Comment by austinaryain** [comment]
Done 👍

**Comment by NehemiahK** [comment]
still shows the index files are different than master. any idea why?

**Comment by austinaryain** [comment]
I can't imagine why, unless you're looking at the diff between my previous commit and the latest? 

I just grabbed the most recent versions of the index files from master. 🤷‍♂

**Comment by NehemiahK** [comment]
alright im merging, here goes nothing

**Pull request merged**
