### PR TITLE
Added Form Component

### PR DESCRIPTION
**Pull request by raghubandaru**
Currently created the Form component and able to send elements required in the form as an array of strings.

### CODE REVIEW

**Comment by NehemiahK** [comment]
interesting approach. would be cool if we could get a v2 for this

**Comment by raghubandaru** [comment]
Hi NehemiahK, v2 in the sense of alternate approach or building upon the existing implementation?

Current implementation works for the default cases and giving a thought on how to implement the cases like <input type="number" /> ( other than the default ones )

**Comment by raghubandaru** [comment]
Like implementing input type=number case and so on

**Comment by NehemiahK** [comment]
Right, just building on the current approach. also we should probably have spacing in between the fields. 

Here's how I image someone using the form. 

I want to create a form passing in what ill need in my form, but I don't want to worry about the ui and the implementation, like I might pass in an onSubmit for the form, but I feel like that's all i would want to do. So also if the fields could have an onChange to update the state maybe? 

Open to suggestions =)

**Comment by wisniewski94** [comment]
@NehemiahK This looks very raw. I think I have better approach with validation using classes. Could you assign me to #4 ? Thanks.

**Pull request merged**
