### PR TITLE
Modal rendering the children passed when triggered

### PR DESCRIPTION
**Pull request by raghubandaru**
Implemented Modal Component with react-modal, and displays all the children that are passed.

### CODE REVIEW

**Comment by NehemiahK** [comment]
Think there's any chance we could do this without using an external library or would that be too difficult?

**Comment by raghubandaru** [comment]
We can build our own modal using portals. I mostly used react-modal for my projects, but will dig into portals if needed.

**Comment by NehemiahK** [comment]
Thanks. the PR is great. Let me know though if you find a better solution

**Comment by raghubandaru** [comment]
Time to get enough rest. I will try to sort this tomorrow 👍

**Comment by raghubandaru** [comment]
Hi NehemiahK, I re-implemented the Modal Component without the need of using library

https://github.com/NehemiahK/Another-React-Lib/pull/83

**Comment by NehemiahK** [comment]
Can you clarify, which do you think is a better solution?

**Comment by raghubandaru** [comment]
Better Solution: https://github.com/NehemiahK/Another-React-Lib/pull/83

Above PR doesn't depend on the react-modal or any external library. Current PR has the dependency on react-modal.

**Pull request closed without merging**
