### PR TITLE
Feature checkbox

### PR DESCRIPTION
**Pull request by willcezar00**
I create a checkbox component without any styling

### CODE REVIEW

**Comment by NehemiahK** [comment]
can you please resolve the conflicts? @willcezar00

**Comment by willcezar00** [comment]
Yes, but I'm at work now, I'll resolve the conflits when I get home.

**Comment by willcezar00** [comment]
Looks like everyone its getting the test fail, I don't know how tests works in react so I can't figure out whats wrong, if you can help me would be great.  I'll try out when I have some free time.

**Comment by NehemiahK** [comment]
sorry, i disabled the tests for now.

**Comment by NehemiahK** [comment]
still shows there are conflicting files though

**Comment by willcezar00** [comment]
Ok, I'll se when I get home

**Comment by willcezar00** [comment]
just solve the conflicts, I already add some styles to checkbox, just waiting this pr goes throught to open another one.

**Comment by NehemiahK** [comment]
sorry still shows there are conflicts

**Comment by willcezar00** [comment]
hope that now goes throught

**Pull request merged**
