### PR TITLE
Add switch element

### PR DESCRIPTION
**Pull request by naclcaleb**

### CODE REVIEW

**Comment by naclcaleb** [comment]
Hmm...it looks like the issue for this no longer exists...

**Comment by naclcaleb** [comment]
Never mind, #46 

If you want to let the other person do it though, that's fine.

**Comment by NehemiahK** [comment]
Ah yeah, next time would be good to claim the issue. But let's see how this progresses. Thanks for the contribution!

**Comment by NehemiahK** [comment]
Closing since it's been done.

**Pull request closed without merging**
