### PR TITLE
Styled link

### PR DESCRIPTION
**Pull request by oskar-kupski-elpassion**
#98

### CODE REVIEW

**Comment by NehemiahK** [comment]
@oskar-kupski-elpassion  please resolve the conflicting files: src/index and demo/src/index

**Comment by oskar-kupski-elpassion** [comment]
@NehemiahK merged

**Comment by NehemiahK** [comment]
still shows conflicts

**Comment by oskar-kupski-elpassion** [comment]
now should be okey - there are no changes in index files

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Pull request merged**
