### PR TITLE
Spinner

### PR DESCRIPTION
**Pull request by oskar-kupski-elpassion**
#119

### CODE REVIEW

**Comment by NehemiahK** [comment]
please resolve conflicts

**Comment by oskar-kupski-elpassion** [comment]
please check now. As you merge another pull requests, mine are
automatically outdated

**Comment by NehemiahK** [comment]
i know im sorry

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Comment by oskar-kupski-elpassion** [comment]
It's done for spinner. Please keep in mind that this component need to have
parent with position relative

**Pull request merged**
