### PR TITLE
#59 Implemented the Sticky Button component

### PR DESCRIPTION
**Pull request by RuchiraRuwantha**
Implemented and styled the sticky button component.

### CODE REVIEW

**Comment by RuchiraRuwantha** [comment]
@NehemiahK, please review the pull request and If there are any needed modifications please let me know.

**Comment by NehemiahK** [comment]
great, i will take a look when i get the chance, thanks

**Comment by NehemiahK** [comment]
@RuchiraRuwantha  please resolve the conflicting files: src/index and demo/src/index

**Comment by RuchiraRuwantha** [comment]
@NehemiahK, the build seem to be failed. I'm new to this so I don't know what the next step is.

**Comment by NehemiahK** [comment]
please resolve the conflicting files

**Comment by RuchiraRuwantha** [comment]
@NehemiahK I resolved the conflicts. Shall I close the issue?

**Comment by NehemiahK** [comment]
can you please just copy whats on master for the index files, i.e., please don't touch the index files, as this is what is creating the conflicts, so if i merge yours others will have this issue

**Comment by RuchiraRuwantha** [comment]
Okay, I'll do that but now there isn't any conflicts.

**Comment by NehemiahK** [comment]
Right, but if i merge yours others will have conflicts.

**Comment by RuchiraRuwantha** [comment]
So, what should I do now?

**Comment by NehemiahK** [comment]
change the index files on master to match your index files so there aren't any changes

**Comment by RuchiraRuwantha** [comment]
So I have to change the index files in your repository in order to make sure there are not any conflicts??

**Comment by NehemiahK** [comment]
no you had to not touch the index files. i update the guidelines to say so, it's fine, im merging it

**Comment by RuchiraRuwantha** [comment]
Okay @NehemiahK. I'm really sorry for the inconvenience.

**Pull request merged**
