### PR TITLE
Add Footer component with light and dark theme

### PR DESCRIPTION
**Pull request by moficodes**
Added a simple footer component.
Has default styling
User can pass light or dark theme.

Fixed some inconsistent stying on the `demo/src/index.js` file
Added footer example in `demo/src/index.js`

### CODE REVIEW

**Comment by NehemiahK** [comment]
Since someone else is working on it, let's wait and see if they do it.

**Comment by moficodes** [comment]
@NehemiahK Sure thing. I did not see someone else was assigned and already worked on it.

**Comment by NehemiahK** [comment]
No worries, if there's no progress i'll reassign and merge yours

**Comment by NehemiahK** [comment]
closing for now. feel free to make a new PR if the issue hasn't been addressed soon

**Comment by moficodes** [comment]
I don’t see any update on this from the original assignee. Should I make a new pull request?

**Comment by iamawaisakram** [comment]
I'm working on it!
Was working on the Card and Card loading skeleton and dynamic table. I submitted all three PRs.

**Pull request closed without merging**
